version: "3"
services:
  redis:
    image: redis
    command: redis-server --requirepass root --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  onair:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    depends_on:
      - redis
    container_name: onair
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
